export const accessoriesOptions = [
  { code: "backpack", title: "Backpack", value: "backpack" },
  { code: "baseball-cap", title: "Baseball Cap", value: "baseball cap" },
  { code: "beanie", title: "Beanie", value: "beanie" },
  { code: "belt", title: "Belt", value: "belt" },
  { code: "bow-tie", title: "Bow Tie", value: "bow tie" },
  { code: "bracelet", title: "Bracelet", value: "bracelet" },
  { code: "cap", title: "Cap", value: "cap" },
  { code: "earrings", title: "Earrings", value: "earrings" },
  { code: "glasses", title: "Glasses", value: "glasses" },
  { code: "handbag", title: "Handbag", value: "handbag" },
  { code: "hat", title: "Hat", value: "hat" },
  { code: "headscarf", title: "Headscarf", value: "headscarf" },
  { code: "hijab", title: "Hijab", value: "hijab" },
  { code: "mask", title: "Mask", value: "mask" },
  { code: "necklace", title: "Necklace", value: "necklace" },
  { code: "ring", title: "Ring", value: "ring" },
  { code: "scarf", title: "Scarf", value: "scarf" },
  { code: "sunglasses", title: "Sunglasses", value: "sunglasses" },
  { code: "tie", title: "Tie", value: "tie" },
  { code: "watch", title: "Watch", value: "watch" },
];
