export const backgroundOptions = [
  {
    code: "default",
    title: "Default",
    value: "use the same background set and surrounding",
  },
  { code: "abstract", title: "Abstract", value: "abstract gradient background" },
  { code: "airport", title: "Airport", value: "airport terminal" },
  { code: "beach", title: "🏖️ Beach", value: "beach, ocean view" },
  { code: "brick-wall", title: "🧱 Brick Wall", value: "brick wall" },
  { code: "bridge", title: "🌉 Bridge", value: "bridge, architectural" },
  { code: "cafe", title: "🍷 Café", value: "café interior" },
  { code: "city", title: "🏙️ City", value: "urban cityscape" },
  { code: "concrete", title: "Concrete", value: "concrete wall" },
  { code: "desert", title: "🏜️ Desert", value: "desert landscape" },
  { code: "forest", title: "🌲 Forest", value: "forest, nature" },
  { code: "garden", title: "🌸 Garden", value: "garden, flowers" },
  { code: "library", title: "📚 Library", value: "library interior" },
  { code: "mountain", title: "🏔️ Mountain", value: "mountain landscape" },
  { code: "night-city", title: "🌃 Night City", value: "city at night, lights" },
  { code: "office", title: "🏢 Office", value: "modern office interior" },
  { code: "park", title: "🏞️ Park", value: "city park, green space" },
  { code: "plain-black", title: "🌙 Plain Black", value: "plain black background" },
  { code: "plain-white", title: "🌼 Plain White", value: "plain white background" },
  { code: "rain", title: "🌧️ Rain", value: "rainy street" },
  { code: "snow", title: "Snow", value: "snowy landscape" },
  { code: "street", title: "Street", value: "urban street, daytime" },
  { code: "studio", title: "Studio", value: "professional studio, white background" },
  { code: "sunset", title: "🌅 Sunset", value: "sunset sky" },
  { code: "wooden", title: "🪵 Wooden", value: "wooden texture background" },
];
