export const bodyShapeOptions = [
  { code: "default", title: "Default", value: "use the same body shape", isSpicy: false },
  { code: "apple-shaped", title: "Apple Shaped", value: "apple-shaped body", isSpicy: false },
  { code: "athletic", title: "Athletic", value: "athletic body", isSpicy: false },
  { code: "average", title: "Average", value: "average body", isSpicy: false },
  { code: "curvy", title: "Curvy", value: "curvy body", isSpicy: false },
  { code: "hourglass", title: "Hourglass", value: "hourglass figure", isSpicy: false },
  { code: "muscular", title: "Muscular", value: "muscular body", isSpicy: false },
  { code: "pear-shaped", title: "Pear Shaped", value: "pear-shaped body", isSpicy: false },
  { code: "petite", title: "Petite", value: "petite body", isSpicy: false },
  { code: "plus-size", title: "Plus Size", value: "plus-size body", isSpicy: false },
  { code: "rectangle", title: "Rectangle", value: "rectangular body shape", isSpicy: false },
  { code: "short", title: "Short", value: "short body", isSpicy: false },
  { code: "slim", title: "Slim", value: "slim body", isSpicy: false },
  { code: "tall", title: "Tall", value: "tall body", isSpicy: false },
];
