export const cameraShotOptions = [
  { code: "bird's-eye-view", title: "Bird's Eye View", value: "bird's eye view" },
  { code: "close-up", title: "Close-up", value: "close-up shot" },
  { code: "dutch-angle", title: "Dutch Angle", value: "dutch angle shot" },
  { code: "extreme-close-up", title: "Extreme Close-up", value: "extreme close-up" },
  { code: "extreme-long-shot", title: "Extreme Long Shot", value: "extreme long shot" },
  { code: "eye-level", title: "Eye Level", value: "eye level shot" },
  { code: "full-body", title: "Full Body", value: "full body shot" },
  { code: "high-angle", title: "High Angle", value: "high angle shot" },
  { code: "long-shot", title: "Long Shot", value: "long shot" },
  { code: "low-angle", title: "Low Angle", value: "low angle shot" },
  { code: "medium-long-shot", title: "Medium Long Shot", value: "medium long shot" },
  { code: "medium-shot", title: "Medium Shot", value: "medium shot" },
  { code: "over-the-shoulder", title: "Over-the-Shoulder", value: "over-the-shoulder shot" },
  { code: "overhead-selfie", title: "Overhead Selfie", value: "overhead selfie shot" },
  { code: "overhead", title: "Overhead", value: "overhead shot" },
  { code: "portrait", title: "Portrait", value: "portrait shot" },
  { code: "profile", title: "Profile", value: "profile shot" },
  { code: "three-quarter", title: "Three-Quarter", value: "three-quarter shot" },
  { code: "two-shot", title: "Two Shot", value: "two shot" },
  { code: "wide-shot", title: "Wide Shot", value: "wide shot" },
  { code: "symmetrical-frame-shot", title: "Symmetrical Frame Shot", value: "symmetrical frame shot" },
];
