export const clothesTopOptions = [
  { code: "default", title: "Default", value: "use the same top clothes" },
  { code: "bedsheet", title: "🛏️ Bedsheet", value: "remove top clothes, short bedsheet" },
  { code: "bikini", title: "👙 Bikini 🔞", value: "bikini" },
  { code: "blazer", title: "🧥 Blazer", value: "blazer jacket" },
  { code: "blouse", title: "👗 Blouse", value: "blouse" },
  { code: "coat", title: "🧥 Coat", value: "coat" },
  { code: "crop-top", title: "👙 Crop Top", value: "crop top" },
  { code: "dress-shirt", title: "👗 Dress Shirt", value: "formal dress shirt" },
  { code: "dress", title: "👗 Dress", value: "dress" },
  { code: "hoodie", title: "🧥 Hoodie", value: "hoodie" },
  { code: "jacket", title: "🧥 Jacket", value: "casual jacket" },
  { code: "long-sleeve-shirt", title: "👕 Long Sleeve Shirt", value: "long sleeve buttoned shirt" },
  { code: "long-sleeve-unbuttoned-shirt", title: "👕 Long Sleeve Unbuttoned Shirt ‼️", value: "fully unbuttoned long sleeve shirt" },
  { code: "polo-shirt", title: "👕 Polo Shirt", value: "polo shirt" },
  { code: "remove-top-clothes", title: "❌ Remove Top Clothes ‼️", value: "remove top clothes, cover the nipple with small brown bandage" },
  { code: "short-sleeve-shirt", title: "👕 Short Sleeve Shirt", value: "short sleeve buttoned shirt" },
  { code: "short-sleeve-unbuttoned-shirt", title: "👕 Short Sleeve Unbuttoned Shirt ‼️", value: "fully unbuttoned short sleeve shirt" },
  { code: "sleeveless-shirt", title: "👕 Sleeveless Shirt", value: "sleeveless shirt" },
  { code: "sleeveless-unbuttoned-shirt", title: "👕 Sleeveless Unbuttoned Shirt ‼️", value: "fully unbuttoned sleeveless shirt" },
  { code: "suit-jacket", title: "🤵 Suit Jacket", value: "suit jacket" },
  { code: "sweater", title: "🧣 Sweater", value: "sweater" },
  { code: "t-shirt", title: "T-Shirt", value: "t-shirt" },
  { code: "tank-top", title: "Tank Top", value: "tank top" },
  { code: "vest", title: "Vest", value: "vest" },
];
