export const clothesBottomOptions = [
  { code: "default", title: "Default", value: "use the same bottom clothes" },
  { code: "bedsheet", title: "Bedsheet", value: "remove bottom clothes, short bedsheet", },
  { code: "bikini-bottom", title: "Bikini Bottom ‼️", value: "bikini bottom" },
  { code: "cargo-pants", title: "Cargo Pants", value: "cargo pants" },
  { code: "chinos", title: "Chinos", value: "chinos" },
  { code: "dress-pants", title: "Dress Pants", value: "formal dress pants" },
  { code: "g-string", title: "G-String ‼️", value: "g-string" },
  { code: "jeans", title: "Jeans", value: "blue jeans" },
  { code: "joggers", title: "Joggers", value: "joggers" },
  { code: "leggings", title: "Leggings", value: "leggings" },
  { code: "long-skirt", title: "Long Skirt", value: "long skirt" },
  { code: "mini-skirt", title: "Mini Skirt", value: "mini skirt" },
  { code: "palazzo-pants", title: "Palazzo Pants", value: "palazzo pants" },
  { code: "remove-bottom-clothes", title: "Remove Bottom Clothes ‼️", value: "remove bottom clothes", },
  { code: "shorts", title: "Shorts", value: "shorts" },
  { code: "skirt", title: "Skirt", value: "skirt" },
  { code: "slim-jeans", title: "Slim Jeans", value: "slim fit jeans" },
  { code: "sweatpants", title: "Sweatpants", value: "sweatpants" },
  { code: "trousers", title: "Trousers", value: "trousers" },
  { code: "wide-leg-pants", title: "Wide Leg Pants", value: "wide leg pants" },
];
