export const colorOptions = [
  { code: "white", title: "White", value: "white" },
  { code: "black", title: "Black", value: "black" },
  { code: "grey", title: "Grey", value: "grey" },
  { code: "navy", title: "Navy", value: "indigo-darken-4" },
  { code: "blue", title: "Blue", value: "blue" },
  { code: "red", title: "Red", value: "red" },
  { code: "green", title: "Green", value: "green" },
  { code: "yellow", title: "Yellow", value: "yellow" },
  { code: "orange", title: "Orange", value: "orange" },
  { code: "pink", title: "Pink", value: "pink" },
  { code: "purple", title: "Purple", value: "purple" },
  { code: "brown", title: "Brown", value: "brown" },
  { code: "beige", title: "Beige", value: "beige" },
  { code: "khaki", title: "Khaki", value: "khaki" },
  { code: "maroon", title: "Maroon", value: "maroon" },
  { code: "cream", title: "Cream", value: "cream" },
  { code: "transparent", title: "Transparent", value: "transparent" },
];
