export const facialExpressionOptions = [
  { code: "default", title: "Default", value: "use the same facial expression" },
  { code: "angry", title: "😠 Angry", value: "angry expression, frowning" },
  { code: "big-smile", title: "😃 Big Smile", value: "big smile, cheerful expression" },
  { code: "confident", title: "😎 Confident", value: "confident expression, self-assured look" },
  { code: "confused", title: "😕 Confused", value: "confused expression, puzzled look" },
  { code: "crying", title: "😭 Crying", value: "crying expression, tears in eyes" },
  { code: "disgusted", title: "🤢 Disgusted", value: "disgusted expression, grimacing" },
  { code: "eyebrow-crease", title: "Eyebrow Crease", value: "eyebrow creates that classic 'pleasure-pain' crease between the brows" },
  { code: "eyes-closed", title: "Eyes Closed", value: "both eyes closed" },
  { code: "fearful", title: "😨 Fearful", value: "fearful expression, scared look" },
  { code: "kissing", title: "😘 Kissing", value: "kissing expression, puckered lips" },
  { code: "laughing", title: "😂 Laughing", value: "laughing, joyful expression" },
  { code: "mouth-open", title: "Mouth Open", value: "mouth Open — degree varies from small 'o' to wide open" },
  { code: "neutral", title: "😐 Neutral", value: "neutral expression, calm face" },
  { code: "sad", title: "😢 Sad", value: "sad expression, melancholic face" },
  { code: "seductive", title: "😏 Seductive", value: "seductive expression, sultry look" },
  { code: "serious", title: "😐 Serious", value: "serious expression, stoic face" },
  { code: "shy", title: "😊 Shy", value: "shy expression, bashful smile" },
  { code: "sleepy", title: "😴 Sleepy", value: "sleepy expression, tired eyes" },
  { code: "smiling", title: "😊 Smiling", value: "smiling, happy expression" },
  { code: "surprised", title: "😲 Surprised", value: "surprised expression, wide eyes" },
  { code: "tongue-out", title: "😛 Tongue Out", value: "tongue out, playful expression" },
  { code: "winking", title: "😉 Winking", value: "winking, playful expression" },
];
