export const facialExpressionOptions = [
  { code: "default", title: "Default", value: "use the same facial expression", isSpicy: false },

  { code: "angry", title: "😠 Angry", value: "angry expression, frowning", isSpicy: false },
  { code: "big-smile", title: "😃 Big Smile", value: "big smile, cheerful expression", isSpicy: false },
  { code: "confident", title: "😎 Confident", value: "confident expression, self-assured look", isSpicy: false },
  { code: "confused", title: "😕 Confused", value: "confused expression, puzzled look", isSpicy: false },
  { code: "crying", title: "😭 Crying", value: "crying expression, tears in eyes", isSpicy: false },
  { code: "disgusted", title: "🤢 Disgusted", value: "disgusted expression, grimacing", isSpicy: false },
  { code: "fearful", title: "😨 Fearful", value: "fearful expression, scared look", isSpicy: false },
  { code: "laughing", title: "😂 Laughing", value: "laughing, joyful expression", isSpicy: false },
  { code: "neutral", title: "😐 Neutral", value: "neutral expression, calm face", isSpicy: false },
  { code: "sad", title: "😢 Sad", value: "sad expression, melancholic face", isSpicy: false },
  { code: "serious", title: "😐 Serious", value: "serious expression, stoic face", isSpicy: false },
  { code: "shy", title: "😊 Shy", value: "shy expression, bashful smile", isSpicy: false },
  { code: "smiling", title: "😊 Smiling", value: "smiling, happy expression", isSpicy: false },
  { code: "surprised", title: "😲 Surprised", value: "surprised expression, wide eyes", isSpicy: false },

  { code: "eyebrow-crease", title: "Eyebrow Crease", value: "eyebrow creates that classic 'pleasure-pain' crease between the brows", isSpicy: true },
  { code: "eyes-closed", title: "Eyes Closed", value: "both eyes closed", isSpicy: true },
  { code: "kissing", title: "😘 Kissing", value: "kissing expression, puckered lips", isSpicy: true },
  { code: "mouth-open", title: "Mouth Open", value: "mouth Open — degree varies from small 'o' to wide open", isSpicy: true },
  { code: "seductive", title: "😏 Seductive", value: "seductive expression, sultry look", isSpicy: true },
  { code: "sleepy", title: "😴 Sleepy", value: "sleepy expression, tired eyes", isSpicy: true },
  { code: "tongue-out", title: "😛 Tongue Out", value: "tongue out, playful expression", isSpicy: true },
  { code: "winking", title: "😉 Winking", value: "winking, playful expression", isSpicy: true },
];
