export const poseOptions = [
  { code: "default", title: "Default", value: "use the same pose", icon: "fi-rr-user", isSpicy: false },

  { code: "arms-crossed", title: "Arms Crossed", value: "standing with arms crossed", icon: "fi-rr-arms-crossed", isSpicy: false },
  { code: "arms-up", title: "Arms Up", value: "standing with arms raised up", icon: "fi-rr-arms-up", isSpicy: false },
  { code: "crouching", title: "Crouching", value: "crouching down", icon: "fi-rr-squat", isSpicy: false },
  { code: "dancing", title: "Dancing", value: "dancing pose, dynamic", icon: "fi-rr-music", isSpicy: false },
  { code: "hands-on-hips", title: "Hands on Hips", value: "standing with hands on hips", icon: "fi-rr-arms-crossed", isSpicy: false },
  { code: "jumping", title: "Jumping", value: "jumping, dynamic action", icon: "fi-rr-jumping", isSpicy: false },
  { code: "kneeling", title: "Kneeling", value: "kneeling on the ground", icon: "fi-rr-squat", isSpicy: false },
  { code: "leaning", title: "Leaning", value: "leaning against wall, casual", icon: "fi-rr-user", isSpicy: false },
  { code: "looking-away", title: "Looking Away", value: "standing, looking away from camera", icon: "fi-rr-eye-crossed", isSpicy: false },
  { code: "lying-down", title: "Lying Down", value: "lying down, relaxed", icon: "fi-rr-sleep", isSpicy: false },
  { code: "lying-flat", title: "Lying Flat", value: "lying flat on the ground, relaxed", icon: "fi-rr-sleep", isSpicy: false },
  { code: "running", title: "Running", value: "running, in motion", icon: "fi-rr-running", isSpicy: false },
  { code: "sitting", title: "Sitting", value: "sitting, relaxed posture", icon: "fi-rr-sitting", isSpicy: false },
  { code: "squatting", title: "Squatting", value: "squatting down", icon: "fi-rr-squat", isSpicy: false },
  { code: "standing", title: "Standing", value: "standing, facing camera", icon: "fi-rr-stand", isSpicy: false },
  { code: "walking", title: "Walking", value: "walking, natural movement", icon: "fi-rr-walking", isSpicy: false },
  { code: "yoga-pose", title: "Yoga Pose", value: "yoga pose, flexible", icon: "fi-rr-yoga", isSpicy: false },

  { code: "69-position", title: "69 Position", value: "69 position", icon: "fi-rr-layers", isSpicy: true },
  { code: "cleavage", title: "Cleavage", value: "slightly visible cleavage without bra", icon: "fi-rr-user", isSpicy: true },
  { code: "doggy-style", title: "Doggy Style", value: "doggy style position", icon: "fi-rr-layers", isSpicy: true },
  { code: "missionary", title: "Missionary", value: "missionary position", icon: "fi-rr-layers", isSpicy: true },
  { code: "pulled-out-shirt", title: "Pulled Out Shirt", value: "shirt pulled out so the belly were visible", icon: "fi-rr-tshirt", isSpicy: true },
  { code: "pulled-up-shirt", title: "Pulled Up Shirt", value: "shirt pulled up so both of shoulders were visible", icon: "fi-rr-tshirt", isSpicy: true },
  { code: "remove-all-clothes", title: "Remove All Clothes", value: "remove all clothes, white bedsheet covering body", icon: "fi-rr-exclamation-triangle", isSpicy: true },
  { code: "reverse-cowgirl", title: "Reverse Cowgirl", value: "reverse cowgirl position", icon: "fi-rr-layers", isSpicy: true },
  { code: "spooning", title: "Spooning", value: "spooning position", icon: "fi-rr-heart", isSpicy: true },
  { code: "spread-thighs", title: "Spread Thighs", value: "thighs slightly spread", icon: "fi-rr-squat", isSpicy: true },
  { code: "unbuttoned", title: "Unbuttoned", value: "fully unbuttoned shirt", icon: "fi-rr-tshirt", isSpicy: true },
  { code: "unbuttoning", title: "Unbuttoning", value: "both hands unbuttoning shirt", icon: "fi-rr-tshirt", isSpicy: true },
];
