export const poseOptions = [
  { code: "default", title: "Default", value: "use the same pose" },
  { code: "69-position", title: "69 Position", value: "69 position" },
  { code: "arms-crossed", title: "Arms Crossed", value: "standing with arms crossed" },
  { code: "arms-up", title: "Arms Up", value: "standing with arms raised up" },
  { code: "cleavage", title: "Cleavage", value: "slightly visible cleavage without bra" },
  { code: "crouching", title: "Crouching", value: "crouching down" },
  { code: "dancing", title: "Dancing", value: "dancing pose, dynamic" },
  { code: "doggy-style", title: "Doggy Style", value: "doggy style position" },
  { code: "hands-on-hips", title: "Hands on Hips", value: "standing with hands on hips" },
  { code: "jumping", title: "Jumping", value: "jumping, dynamic action" },
  { code: "kneeling", title: "Kneeling", value: "kneeling on the ground" },
  { code: "leaning", title: "Leaning", value: "leaning against wall, casual" },
  { code: "looking-away", title: "Looking Away", value: "standing, looking away from camera" },
  { code: "lying-down", title: "Lying Down", value: "lying down, relaxed" },
  { code: "lying-flat", title: "Lying Flat", value: "lying flat on the ground, relaxed" },
  { code: "missionary", title: "Missionary", value: "missionary position" },
  { code: "pulled-out-shirt", title: "Pulled Out Shirt", value: "shirt pulled out so the belly were visible", },
  { code: "pulled-up-shirt", title: "Pulled Up Shirt", value: "shirt pulled up so both of shoulders were visible", },
  { code: "remove-all-clothes", title: "Remove All Clothes ‼️", value: "remove all clothes, white bedsheet covering body" },
  { code: "reverse-cowgirl", title: "Reverse Cowgirl", value: "reverse cowgirl position" },
  { code: "running", title: "🏃 Running", value: "running, in motion" },
  { code: "sitting", title: "🧍 Sitting", value: "sitting, relaxed posture" },
  { code: "spooning", title: "Spooning", value: "spooning position" },
  { code: "spread-thighs", title: "Spread Thighs", value: "thighs slightly spread" },
  { code: "squatting", title: "Squatting", value: "squatting down" },
  { code: "standing", title: "🧍 Standing", value: "standing, facing camera", },
  { code: "unbuttoned", title: "🧍 Unbuttoned ‼️", value: "fully unbuttoned shirt" },
  { code: "unbuttoning", title: "🧍 Unbuttoning", value: "both hands unbuttoning shirt" },
  { code: "walking", title: "🧍 Walking", value: "walking, natural movement" },
  { code: "yoga-pose", title: "Yoga Pose", value: "yoga pose, flexible" },
];
