export const presetOptions = [
  {
    id: 1,
    name: "Casual",
    icon: "mdi-tshirt-crew",
    pose: ["standing"],
    facialExpression: ["default"],
    topClothes: "t-shirt",
    topClothesColor: "",
    bottomClothes: "jeans",
    bottomClothesColor: "",
    cameraShot: "medium-shot",
    background: "street",
  },
  {
    id: 2,
    name: "Formal",
    icon: "mdi-tie",
    pose: ["standing, facing camera"],
    facialExpression: ["default"],
    topClothes: "dress-shirt",
    topClothesColor: "white",
    bottomClothes: "formal dress pants",
    bottomClothesColor: "black",
    cameraShot: "portrait shot",
    background: "professional studio, white background",
  },
  {
    id: 3,
    name: "Sporty",
    icon: "mdi-run",
    pose: ["running, in motion", "walking, natural movement"],
    facialExpression: ["default"],
    topClothes: "tank-top",
    topClothesColor: "",
    bottomClothes: "sweatpants",
    bottomClothesColor: "",
    cameraShot: "full body shot",
    background: "city park, green space",
  },
  {
    id: 4,
    name: "Beach",
    icon: "mdi-beach",
    pose: ["standing, facing camera", "walking, natural movement"],
    facialExpression: ["default"],
    topClothes: "bikini-top",
    topClothesColor: "",
    bottomClothes: "bikini bottom",
    bottomClothesColor: "",
    cameraShot: "wide shot",
    background: "beach, ocean view",
  },
  {
    id: 5,
    name: "Office",
    icon: "mdi-office-building",
    pose: ["sitting, relaxed posture"],
    facialExpression: ["default"],
    topClothes: "long-sleeve-shirt",
    topClothesColor: "white",
    bottomClothes: "formal dress pants",
    bottomClothesColor: "black",
    cameraShot: "medium shot",
    background: "modern office interior",
  },
  {
    id: 6,
    name: "Half open shoulder",
    icon: "",
    pose: ["kneeling", "unbuttoned", "cleavage", "pulled-up-shirt", "pulled-out-shirt", "spread-thighs"],
    facialExpression: ["default"],
    topClothes: "short-sleeve-unbuttoned-shirt",
    topClothesColor: "white",
    bottomClothes: "mini-skirt",
    bottomClothesColor: "black",
    cameraShot: "close-up",
    background: "default",
  },
  {
    id: 7,
    name: "Bedsheet",
    icon: "",
    pose: ["remove-all-clothes", "lying-flat", 'spread-thighs'],
    facialExpression: ["default"],
    topClothes: "",
    topClothesColor: "",
    bottomClothes: "",
    bottomClothesColor: "",
    cameraShot: "overhead-selfie",
    background: "default",
  },
];
